import type { Metadata } from "next";
import { Exo_2, Geist, Geist_Mono, Roboto, Sora } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable:"--font-roboto",
  subsets:["cyrillic"],
  weight:["400"]
});

const exo = Exo_2({
  variable:"--font-exo",
  subsets:["cyrillic"],
  weight:["300"]
});
const sora = Sora({
  variable:"--font-sora",
  subsets:["latin"],
  weight:["500"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${exo.variable} ${sora.variable} antialiased`}
      >
        <Provider>
        {children}
        </Provider>
        
  
        
      </body>
    </html>
  );
}
